#!/bin/bash
set -euo pipefail

set -x

echo "--- Searching for Clowns 🤡"
echo "$BUILDKITE_BUILD_CHECKOUT_PATH"

pwd
ls

docker images
docker ps

echo "--- Disk quota"
df -h

if grep -inr -C1 "🤡" . ; then
  echo "^^^ +++"
  echo "+++ :warning: Detected clowns! 🔪"
  exit 1
fi
